cargo-features = ["edition2024"]

[package]
name = "tttui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.27.0"

[profile.release]
opt-level = 3
debug = false
lto = "fat"
panic = "abort"
strip = "symbols"
codegen-units = 1